# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171018_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94718a56-c8e8-4b21-a678-afebe78743ed'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
